# **Numpy**
The NumPy library is the core library for scientific computing in
 Python.
It provides a high-performance multidimensional array
 object, and tools for
working with these arrays.


In [47]:
#Use the following import convention:
import numpy as np

## Creating Arrays


In [48]:
#One Dimentional numpy array
a = np.array([1,2,3])
print(a)
#Two Dimentional numpy array
b = np.array([(1.5,2,3), (4,5,6)])
print(b)
#Three Dimentional numpy array
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float) # Specifying datatype is not necessary
print(c)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


## Initial Placeholders

In [49]:
#Create an array of zeros
print(np.zeros((3,4)))
#Create an array of ones
print(np.ones((2,3,4),dtype=np.int16))
#Create an array of evenly spaced values (number of samples)
print(np.linspace(0,2,9))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [50]:
#Create an array with random values
print(np.random.random((2,2)))
#Create an empty array
print(print(np.empty((3,2))))
#Create an array of evenly spaced values (step value)
d = np.arange(10,25,5)
print(d)

[[0.58978894 0.92631016]
 [0.26978851 0.09575151]]
[[1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]]
None
[10 15 20]


In [51]:
#Create a constant array
e = np.full((2,2),7)
print(e)
#Create a 2X2 identity matrix
f = np.eye(2)
print(f)

[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]


##**I/O**
## Saving & Loading On Disk

In [52]:
# Saving the array in the 'my_array.npy' file
np.save('my_array', a)

# Saving the array object in the 'array.npz' file
np.savez('array.npz', a, b)

# Loading the already existing file
np.load('my_array.npy')

array([1, 2, 3])

## Saving & Loading Text Files

In [55]:
#Library for importing files to Google Colab
from google.colab import files
#Importing text file to Google Colab
files.upload()

Saving ToNumpy.txt to ToNumpy (1).txt


{'ToNumpy (1).txt': b'24 1 2 3 53 12 3 19 20 \r\n'}

In [56]:
# loading the values from the text file to numpy
np.loadtxt("ToNumpy.txt")

array([24.,  1.,  2.,  3., 53., 12.,  3., 19., 20.])

In [57]:
#Importing CSV file to Google Colab
files.upload()

Saving ToNumpy.csv to ToNumpy (1).csv


{'ToNumpy (1).csv': b'2,3,4,5,6,7,8'}

In [60]:
# Loading the CSV file to numpy array
np.genfromtxt("ToNumpy.csv", delimiter=',')

array([2., 3., 4., 5., 6., 7., 8.])

In [61]:
np.savetxt("./FromNumpy.txt", a, delimiter=" ")

## Asking For Help

In [62]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


## Inspecting Your Array

In [63]:
#Array dimensions
print(a.shape)
#Length of array
print(len(a))
#Number of array dimensions
print(b.ndim)
#Convert an array to a different type
print(b.astype(int))

(3,)
3
2
[[1 2 3]
 [4 5 6]]


In [64]:
#Number of array elements
print(e.size)
#Data type of array elements
print(b.dtype)
#Name of data type
print(b.dtype.name)

4
float64
float64


## Data Types

In [65]:
#Signed 64-bit integer types
np.int64
#Standard double-precision floating point
np.float32
#Complex numbers represented by 128 floats
np.complex
#Boolean type storing TRUE and FALSE values
np.bool
#Python object type
np.object
#Fixed-length string type
np.string_
#Fixed-length unicode type
np.unicode_

<ipython-input-65-0e94ef1a2bed>:6: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.complex
<ipython-input-65-0e94ef1a2bed>:8: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool
<ipython-input-65-0e94ef1a2bed>:10: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` b

numpy.str_

## **Array Mathematics**
## Arithmetic Operations

In [66]:
#Addition using operator
print(b + a)
#Addition using NumPy class method
np.add(b,a)

[[2.5 4.  6. ]
 [5.  7.  9. ]]


array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [67]:
#Subraction using operator
g = a - b
print(g)
#Subraction using NumPy class method
np.subtract(a,b)

[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]


array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [68]:
#Multiply using operator
print(a * b)
#multiply using NumPy class method
np.multiply(a, b)

[[ 1.5  4.   9. ]
 [ 4.  10.  18. ]]


array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [69]:
#Divide using operator
print(a / b)
#Divide using NumPy class method
np.divide(a, b)

[[0.66666667 1.         1.        ]
 [0.25       0.4        0.5       ]]


array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [70]:
#Exponentiation
print(np.exp(b))
#Square root
print(np.sqrt(b))
#Print sines of an array
print(np.sin(a))
#Element-wise cosine
print(np.cos(b))
#Element-wise natural logarithm
print(np.log(a))
#Dot product
print(e.dot(f))

[[  4.48168907   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[1.22474487 1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[0.84147098 0.90929743 0.14112001]
[[ 0.0707372  -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
[0.         0.69314718 1.09861229]
[[7. 7.]
 [7. 7.]]


## Comparison

In [71]:
#Element-wise comparison
a == b

array([[False,  True,  True],
       [False, False, False]])

In [72]:
#Element-wise comparison
a < 2

array([ True, False, False])

In [73]:
#Array-wise comparison
np.array_equal(a, b)

False

## Aggregate Functions

In [74]:
#Array-wise  sum
print(a.sum())
#Array-wise  minimum  value
print(a.min())
#Maximum  value  of  an  array  row
print(b.max(axis=0))
#Cumulative sum of the elements
print(b.cumsum(axis=1))
#Mean
print(a.mean())
#Median
print(np.median(b))
#Correlation  coefficient
print(np.corrcoef(a))
#Standard  deviation
print(np.std(b))

6
1
[4. 5. 6.]
[[ 1.5  3.5  6.5]
 [ 4.   9.  15. ]]
2.0
3.5
1.0
1.5920810978785667


## **Copying Arrays**

In [75]:
#Create a view of the array with the same data
h = a.view()
print(h)
#Create a copy of the array
print(np.copy(a))
#Create a deep copy of the array
h = a.copy()
print(h)

[1 2 3]
[1 2 3]
[1 2 3]


## **Sorting Arrays**

In [76]:
#Sort an array
a.sort()
#Sort the elements of an array's axis
c.sort(axis=0)

## **Subsetting, Slicing, Indexing**
## Subsetting

In [77]:
#Select the element at the 2nd index
print(a[2])
#Select the element at row 1 column 2 (equivalent to b[1][2])
print(b[1,2])

3
6.0


## Slicing

In [78]:
#Select items at index 0 and 1
print(a[0:2])
#Select items at rows  0 and 1 in column 1
print(b[0:2,1])
#Select all items at row  0 (equivalent to b[0:1, :])
print(b[:1])
#Same as [1,:,:]
print(c[1,...])
#Reversed array a array([3, 2, 1])
print(a[ : :-1])

[1 2]
[2. 5.]
[[1.5 2.  3. ]]
[[3. 2. 3.]
 [4. 5. 6.]]
[3 2 1]


## Boolean Indexing

In [79]:
#Select elements from a less than 2
print(a[a<2])

[1]


## Fancy Indexing

In [80]:
#Select elements (1,0),(0,1),(1,2) and (0,0)
print(b[[1,  0,  1,  0],[0,  1, 2, 0]])
#Select a subset of the matrix’s rows  and columns
print(b[[1,  0,  1,  0]][:,[0,1,2,0]])

[4.  2.  6.  1.5]
[[4.  5.  6.  4. ]
 [1.5 2.  3.  1.5]
 [4.  5.  6.  4. ]
 [1.5 2.  3.  1.5]]


## **Array Manipulation**
## Transposing Array

In [81]:
#Permute array dimensions
i = np.transpose(b)
print(i)
#Permute array dimensions
i.T

[[1.5 4. ]
 [2.  5. ]
 [3.  6. ]]


array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

## Changing Array Shape

In [82]:
#Flatten the array
print(b.ravel())
#Reshape, but don’t change data
print(g.reshape(3,-2))

[1.5 2.  3.  4.  5.  6. ]
[[-0.5  0. ]
 [ 0.  -3. ]
 [-3.  -3. ]]


## Adding/Removing Elements

In [83]:
#Return a new array with shape (2,6)
h.resize((3,1))
print(h)
#Append items to an array
print(np.append(h,g))
#Insert items in an array
print(np.insert(a, 1, 5))
#Delete items from an array
print(np.delete(a,[1]))

[[1]
 [2]
 [3]]
[ 1.   2.   3.  -0.5  0.   0.  -3.  -3.  -3. ]
[1 5 2 3]
[1 3]


## Combining Arrays

In [84]:
#Concatenate arrays
print(np.concatenate((a,d),axis=0))
#Stack arrays vertically (row-wise)
print(np.vstack((a,b)))
#Stack arrays vertically (row-wise)
print(np.r_[e,f])
#Stack arrays horizontally (column-wise)
print(np.hstack((e,f)))
#Create stacked column-wise arrays
print(np.column_stack((a,d)))
#Create stacked column-wise arrays
print(np.c_[a,d])

[ 1  2  3 10 15 20]
[[1.  2.  3. ]
 [1.5 2.  3. ]
 [4.  5.  6. ]]
[[7. 7.]
 [7. 7.]
 [1. 0.]
 [0. 1.]]
[[7. 7. 1. 0.]
 [7. 7. 0. 1.]]
[[ 1 10]
 [ 2 15]
 [ 3 20]]
[[ 1 10]
 [ 2 15]
 [ 3 20]]


## Splitting Arrays

In [85]:
#Split the array horizontally at the 3rd  index
print(np.hsplit(a,3))
#Split the array vertically at the 2nd index
np.vsplit(c,2)

[array([1]), array([2]), array([3])]


[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]),
 array([[[3., 2., 3.],
         [4., 5., 6.]]])]